### ISSUE TITLE
Sanic v21.9.0: TypeError: __init__() missing 1 required positional argument: 'fallback'

### ISSUE THREAD

**Issue by Basit-qc** [ashleysommer/sanic-cors#53]
With latest Sanic v21.9.0, 
Following line is breaking with error: 
```
CORS(app, origins=CORS_ORIGIN_LIST)
```
Error:
```
TypeError: __init__() missing 1 required positional argument: 'fallback'
```

**Comment by ashleysommer** [comment]
Hi @Basit-qc  (and all others who have visited this Issue)
I've released Sanic-CORS v1.0.1 to address this issue. Can you please test it to see if it fixes the problem in your application.
This update also requires an update to Sanic v21.9.1 and sanic-plugin-toolkit to v1.2.0 to work properly.

**Comment by Basit-qc** [comment]
Hi @ashleysommer, 
Thank you for the prompt response and quick fix. It is now working fine with sanic v21.9.1 👍
